version: '3'
services:
  db:
    image: mariadb:10
    tty: true
    restart: always
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: practice
    ports:
      - 3306:3306
volumes:
  db_volume:
