// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"strconv"

	"github.com/dolthub/go-mysql-server/memory"
	simsql "github.com/dolthub/go-mysql-server/sql"
	"github.com/volatiletech/null/v8"
)

func CreateDummyProductTable(db *memory.Database) *memory.Table {
	tableName := "product"
	table := memory.NewTable(tableName, simsql.NewPrimaryKeySchema(simsql.Schema{
		{Name: "id", Type: simsql.Text, Nullable: false, Source: tableName, PrimaryKey: true},
		{Name: "name", Type: simsql.Text, Nullable: false, Source: tableName, PrimaryKey: false},
		{Name: "price", Type: simsql.Int64, Nullable: false, Source: tableName, PrimaryKey: false},
		{Name: "category_id", Type: simsql.Text, Nullable: true, Source: tableName, PrimaryKey: false},
	}), db.GetForeignKeyCollection())

	return table
}

// HACK: only for consuming unused imports
var _ = strconv.Itoa(42)
var _ null.String
